### ISSUE TITLE
spec is failing falsely

### ISSUE THREAD

**Issue by zevaverbach** [learn-co-curriculum/greeting-cli#11]
This should pass, but doesn't:

``` ruby
def greeting(name)
  puts "Hello #{name}. It's nice to meet you."
end
```

**Comment by AnnJohn** [comment]
Hi @zevav it looks like your solution is correct but there might be another reason why it's not passing. For immediate help with any Readme or Lab, please use the Ask a Question tool within Learn and someone from our instructor expert support team will get back to you right away. Thanks!

**Comment by zevaverbach** [comment]
Thanks, AnnJohn, but I'm not getting useful help via Ask a Question,
unfortunately.
