### ISSUE TITLE
Couldn't open bin file in Xcode

### ISSUE THREAD

**Issue by crickycicchetti** [learn-co-curriculum/greeting-cli#13]
I couldn't open bin/greeting from my terminal. I had to cd into the bin directory, use "open .", and drag the file icon into Xcode in order to open it up. I've attached a screenshot of what happened when I tried "open greet" when inside greeting-cli-hh-000/bin.
![screen shot 2015-12-30 at 7 02 57 pm](https://cloud.githubusercontent.com/assets/12304346/12059375/10df3454-af28-11e5-9ead-5a442fb4d411.png)

**Comment by AnnJohn** [comment]
hey cricky, going to close this one since with the IDE, this shouldn't be an issue. But also you shouldn't have to use Xcode at all for this. If this is still a problem, just find me!
