### ISSUE TITLE
The tests check for gets, but not gets.strip

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-curriculum/greeting-cli#21]
My code passes the tests regardless of whether I write gets or gets.strip. 
The result of using gets instead of gets.strip could be output such as:

Hi! I'm HAL, what's your name?
Jack
Hello Jack                                                                         . It's nice to meet you.

What we want is this:

Hi! I'm HAL, what's your name?
Jack
Hello Jack. It's nice to meet you.

It's not a big issue, but the tests need to make sure that gets.strip, rather than gets, is called in the bin/greet file. Thanks for looking into this!

**Comment by sgharms** [comment]
Hi @Sdcrouse , we've added a test to cover your case. Thanks
