### ISSUE TITLE
Wrong explanation

### ISSUE THREAD

**Issue by YevgeniySob** [learn-co-curriculum/greeting-cli#27]
In Part II: The CLI it says to use a strip and chomp methods to remove the "white spaces" and "\n", but in the test, in greeting_spec.rb it clearly states that that part has to be taken in the function itself!

it 'greets the person with additional whitespace removed' do
      allow($stdout).to receive(:puts)

      output = capture_puts{ greeting(" Sally\t   ") }

**Comment by bcorey85** [comment]
Had the same issue.

**Comment by drakeltheryuujin** [comment]
Hi @YevgeniySob,

Thank you for spotting this issue and providing feedback!
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
