### ISSUE TITLE
Local build light flips green after getting the Part 1 tests to pass

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/greeting-cli#3]
Because we pass only one file to be tested, once those tests pass Learn thinks we're done. Wonder if we should instruct to just run learn instead?

**Comment by aviflombaum** [comment]
Interesting - i think that's an improvement for the learn test runner, only count full tests run. cc @loganhasson

**Comment by loganhasson** [comment]
@aviflombaum @matbalez do you mean running `learn some_spec.rb` doesn't just run that one file?

**Comment by matbalez-zz** [comment]
running `learn some_spec.rb` does just run that one file, but it also flips the light green. i think the latter is undesirable. light should only flip green from a clear run of `learn` e.g. all tests passing

**Comment by loganhasson** [comment]
ah, ok. phew (running one file didn't work in the past and i was certain i fixed it...glad it didn't re-break). so yeah, for this we'll need to think about how we actually want to handle it. the gem (well, rspec actually) just reports the totally number of examples run vs the total number of passing examples. we'll need to figure out where we decide what the total number of examples is. is it in the .learn file? does the gem need to somehow parse it from a spec structure that could be infinitely variable? and what's the user experience on Learn look like? if i run one spec file, but all of those tests pass, do i get a red light on Learn? do i get no light? do I get a different colored light?

**Comment by matbalez-zz** [comment]
i think the light on learn stays red until all tests pass with `learn`
figuring out how many total passing examples is trickier. not sure. 

an alternative way to think about this might be: when we want user to test a single file, we tel them to use `rspec filename` and run learn only at the end when all of the tests in individual spec files are passing? but that's kind of sidestepping the problem.
